# Learning Pytorch Basics

In [2]:
import torch

In [6]:
#Construct 5 empty, uninitialized:
x = torch.empty(5)
print(x)
#Construct a 5x3 matrix, uninitialized:
x = torch.empty(5,3)
print(x)

tensor([ 0.0000e+00, -4.6566e-10,  7.4378e+13,  2.0005e+00,  1.1402e-30])
tensor([[ 0.0000e+00, -4.6566e-10,  7.4399e+13],
        [ 1.0845e-19, -3.6894e+19,  1.0446e+02],
        [ 0.0000e+00,  2.0001e+00,  2.0000e+00],
        [ 3.4928e-04,  1.4013e-45,  0.0000e+00],
        [ 0.0000e+00, -4.6566e-10,  7.4397e+13]])


In [13]:
#Constructing randomized 5x3 Matrix
x = torch.rand(5,3)
print(x)

tensor([[0.5375, 0.1566, 0.4623],
        [0.6512, 0.8593, 0.7143],
        [0.0693, 0.0313, 0.3630],
        [0.9025, 0.4619, 0.9500],
        [0.8488, 0.1385, 0.0900]])


In [16]:
#Constructing randomized 5x3 with zeros 
x= torch.zeros(5,3,dtype= torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [18]:
#Constructing a tensor directly from the data 
x = torch.tensor([5.4,3])
print(x)

tensor([5.4000, 3.0000])


In [22]:
#Creating a tensor from an existing datatype

x = torch.zeros(5,3,dtype=torch.long)

x = torch.rand_like(x,dtype= torch.float)

print(x)

tensor([[0.9370, 0.0049, 0.4875],
        [0.3693, 0.5424, 0.6939],
        [0.4644, 0.0488, 0.3529],
        [0.3243, 0.4094, 0.3259],
        [0.1197, 0.9680, 0.8403]])


In [24]:
#Get the size of a tensor 

print(x.size())

torch.Size([5, 3])


# Operations

In [26]:
y = torch.rand(5,3)
print(y)

tensor([[0.4185, 0.8742, 0.4164],
        [0.4195, 0.5481, 0.5949],
        [0.6831, 0.2599, 0.9327],
        [0.4801, 0.6616, 0.0079],
        [0.1232, 0.4802, 0.4668]])


In [30]:
#syntax 1 
print(x+y)

tensor([[1.3554, 0.8791, 0.9039],
        [0.7888, 1.0906, 1.2888],
        [1.1476, 0.3087, 1.2857],
        [0.8044, 1.0710, 0.3338],
        [0.2429, 1.4481, 1.3071]])


In [31]:
#syntax 2
print(torch.add(x,y))

tensor([[1.3554, 0.8791, 0.9039],
        [0.7888, 1.0906, 1.2888],
        [1.1476, 0.3087, 1.2857],
        [0.8044, 1.0710, 0.3338],
        [0.2429, 1.4481, 1.3071]])


## providing an output tensor as argument



In [33]:
result = torch.empty(5,3)
torch.add(x,y, out = result)
print(result)

tensor([[1.3554, 0.8791, 0.9039],
        [0.7888, 1.0906, 1.2888],
        [1.1476, 0.3087, 1.2857],
        [0.8044, 1.0710, 0.3338],
        [0.2429, 1.4481, 1.3071]])


In [35]:
#addition in place
# adds x to y
y.add_(x)
print(y)

tensor([[2.2924, 0.8841, 1.3914],
        [1.1582, 1.6330, 1.9828],
        [1.6120, 0.3576, 1.6386],
        [1.1287, 1.4805, 0.6596],
        [0.3626, 2.4161, 2.1473]])


In [44]:
#indexing and printing 
print(x[:,1])

tensor([0.0049, 0.5424, 0.0488, 0.4094, 0.9680])


In [48]:
#Resizing: If you want to resize/reshape tensor, you can use torch.view:
x  =torch.randn(4,4)
y = x.view(16)
z = x.view(-1,8)
print(x.size(),y.size(),z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [53]:
print(y)
print(z)

tensor([ 0.0069,  0.1560,  1.1981, -0.3258, -0.1495,  0.6767,  2.5759, -0.0536,
         0.0165,  0.8406, -0.1742, -0.3860,  0.2574,  0.5984,  0.1393, -1.0650])
tensor([[ 0.0069,  0.1560,  1.1981, -0.3258, -0.1495,  0.6767,  2.5759, -0.0536],
        [ 0.0165,  0.8406, -0.1742, -0.3860,  0.2574,  0.5984,  0.1393, -1.0650]])


In [55]:
# have a one element tensor, use .item() to get the value as a Python number

x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.7892])
-0.7892212271690369


# NUMPY To Tensor and Tensor To NUMPY

## Torch Tensor to a NumPy Array

In [61]:
a = torch.randn(12)
print(a)

tensor([ 1.6665,  0.3484,  1.0953, -1.2449,  0.4130,  0.0505,  0.3711, -0.1370,
        -0.6423,  0.7896, -0.9151,  0.8831])


In [63]:
b = a.numpy()
print(b)

[ 1.6664938   0.3483733   1.0953215  -1.2448642   0.4130459   0.05045652
  0.37106064 -0.13696414 -0.64230376  0.7895807  -0.91509163  0.8830803 ]


## NumPy Array to a Torch Tensor

In [70]:
import numpy as np
a = np.ones(5)
print(a)

[1. 1. 1. 1. 1.]


In [72]:
b = torch.from_numpy(a)
print(b)

tensor([1., 1., 1., 1., 1.], dtype=torch.float64)
